[package]
name = "gir"
version = "0.0.1"
authors = [
	"Evgenii Pashkin <eapashkin@gmail.com>",
	"Gleb Kozyrev <gleb@gkoz.com>",
	"Guillaume Gomez <guillaume1.gomez@gmail.com>",
]
build = "build.rs"
exclude = ["Gir*.toml", "tests/**/*", "*.md"]

[dependencies]
docopt = "*"
xml-rs = "0.2.1"
toml = "*"
case = "*"
env_logger = "*"
git2 = "*"
lazy_static = "*"
log = "*"
regex = "*"
time = "*"
hprof = "*"
rustdoc-stripper = { git = "https://github.com/GuillaumeGomez/rustdoc-stripper" }

[dependencies.quick-error]
git = "http://github.com/tailhook/quick-error"
branch = "context2"

[build-dependencies]
git2 = "*"

[profile.release]
codegen-units = 4
